<?php
/**
 * Transform the api doc generated by clean/phpdoc-md (see https://github.com/piko-framework/piko) to be compatible
 * with the Jekyll theme just-the-doc
 *
 */
$srcDir = __DIR__ . '/piko/api';
$destDir = __DIR__ . '/docs/api';

/*
 * if (file_exists($apiDir . '/README.md')) {
 * rename($apiDir . '/README.md', $apiDir . '/index.md');
 * }
 */
function prepend($file, $prepend)
{
    $fp = fopen($file, 'r+');
    $chunkLength = strlen($prepend);

    $i = 0;
    do {
        $readData = fread($fp, $chunkLength);
        fseek($fp, $i * $chunkLength);
        fwrite($fp, $prepend);

        $prepend = $readData;
        $i ++;
    } while ($readData);

    fclose($fp);
}

$files = scandir($srcDir);
$matches = [];

foreach ($files as $file) {

    if ($file == '.' || $file == '..')  {
        continue;
    }

    $destFile = $destDir . '/' . $file;
    $srcFile = $srcDir . '/' . $file;
    $header = '';

    if ($file == 'README.md') {
        $destFile =  $destDir . '/' . 'index.md';
        $header = <<<EOL
---
layout: default
title: API
has_children: true
has_toc: false
---

EOL;
    }

    if (preg_match('/(.*)\.md$/', $file, $matches)) {

        $header = <<<EOL
---
layout: default
title: {$matches[1]}
parent: API
---


EOL;
    }
    if (!file_exists($destFile)) {
        file_put_contents($destFile, $header . file_get_contents($srcFile));
    }
    elseif (md5_file($srcFile) != md5_file($destFile)) {
         file_put_contents($destFile, $header . file_get_contents($srcFile));
    }
}


