<?php
/**
 * Transform the api doc generated by clean/phpdoc-md (see https://github.com/piko-framework/piko) to be compatible
 * with the Jekyll theme just-the-doc
 *
 */
$srcDir = __DIR__ . '/piko/api';
$destDir = __DIR__ . '/docs/api';

$files = scandir($srcDir);
$matches = [];

foreach ($files as $file) {

    if ($file == '.' || $file == '..')  {
        continue;
    }

    $destFile = $destDir . '/' . $file;
    $srcFile = $srcDir . '/' . $file;
    $header = '';

    if ($file == 'README.md') {
        $destFile =  $destDir . '/' . 'index.md';
        $header = <<<EOL
---
layout: default
title: API
has_children: true
has_toc: false
nav_order: 20
---


EOL;
    }

    elseif (preg_match('/(.*)\.md$/', $file, $matches)) {

        $header = <<<EOL
---
layout: default
title: {$matches[1]}
parent: API
---


EOL;
    }
    if (!file_exists($destFile)) {
        file_put_contents($destFile, $header . file_get_contents($srcFile));
    }
    elseif (md5_file($srcFile) != md5_file($destFile)) {
         file_put_contents($destFile, $header . file_get_contents($srcFile));
    }
}


