<?php
/**
 * Transform the api doc generated by clean/phpdoc-md (see https://github.com/piko-framework/piko) to be compatible 
 * with the Jekyll theme just-the-doc
 * 
 */

$apiDir = dirname(__DIR__) . '/docs/api';

if (file_exists($apiDir . '/README.md')) {
	rename($apiDir . '/README.md', $apiDir . '/index.md');
}

function prepend($file, $prepend)
{
	$fp = fopen($file, 'r+');
	$chunkLength = strlen($prepend);

	$i = 0;
	do{
		$readData = fread($fp, $chunkLength);
		fseek($fp, $i * $chunkLength);
		fwrite($fp, $prepend);

		$prepend = $readData;
		$i++;
	} while ($readData);

	fclose($fp);
}

$files = scandir($apiDir);
$matches = [];

foreach($files as $file) {
	if ($file == 'index.md') {
$header = <<<EOL
---
layout: default
title: API
has_children: true
has_toc: false
---


EOL;
		prepend($apiDir . '/' . $file, $header);
		continue;
	}

	if (preg_match('/(.*)\.md$/', $file, $matches)) {

$header = <<<EOL
---
layout: default
title: {$matches[1]}
parent: API
---


EOL;
		prepend($apiDir . '/' . $file, $header);
	}
}


